#!/bin/bash
#
# conf_files       Updates node configuration files at startup
#
# chkconfig: 3 20 80
# description: Updates node configuration files at startup
#
# $Id: nm.init,v 1.1 2006/11/13 20:04:44 mlhuang Exp $

# Source function library.
. /etc/init.d/functions

case "$1" in
    start|restart|reload)
	action $"Updating node configuration files: " python /usr/share/NodeManager/conf_files.py
	;;
    *)
	echo $"Usage: $0 {start|restart}"
	exit 1
esac

exit 0
